apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
data:
  index.html: |
      <!DOCTYPE html>
      <html>
      <head>
      <title>Welcome!</title>
      </head>
      <body>
      <h1>Hello from my ConfigMap!</h1>
      <p>This page is being served by NGINX, but the content is managed externally by Kubernetes.</p>
      </body>
      </html>
  